version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/JaFlaskWebDbAppSrvr
hooks:
  ApplicationStop:
   - location: scripts/deregister_from_elb.sh
     timeout: 300
  BeforeInstall:
   - location: scripts/before_install.sh
     timeout: 300
  AfterInstall:
   - location: scripts/install_dependencies.sh
     timeout: 300
  ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
  ValidateService:
    - location: scripts/monitor_service.sh
      timeout: 3600