version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/JaFlaskWebDbApp/
permissions:
  - object: /home/ec2-user/JaFlaskWebDbApp/scripts
    mode: 777
    pattern: "**"    
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
