apiVersion: v1
kind: Service
metadata:
  name: ja-flask-app-service
  labels:
    app: flask-app-service
  namespace: ja-env1
spec:
  selector:
    app: ja-flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # Port accessible inside cluster
      targetPort: 8080 # Port accessible inside the pod
      nodePort: 30001 # Port accessible outside cluster