# apiVersion: v1
# kind: Service
# metadata:
#   name: ja-mongo-db-service
#   labels:
#     app: mongo-db-service
# spec:
#   selector:
#     app: ja-mongo-db
#   ports:
#     - protocol: TCP
#       port: 27017
#       targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ja-flask-app-service
  labels:
    app: flask-app-service
spec:
  selector:
    app: ja-flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080 # Port accessible inside cluster
      targetPort: 8080 # Port accessible inside the pod
      nodePort: 30001 # Port accessible outside cluster