apiVersion: apps/v1
kind: Deployment
metadata:
  name: ja-flask-app-deployment
  labels:
    app: ja-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ja-flask-app
  template:
    metadata:
      labels:
        app: ja-flask-app
    spec:
      containers:
        - name: flask-app-image
          image: 
          valueFrom:
           - configMapKeyRef:
              name: ja-flask-configmap
              key: image_location
          ports:
            - containerPort: 8080
          # env:
          #   - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-creds
          #         key: mongodbadmin-username
          #   - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-creds
          #         key: mongodbadmin-password
          #   - name: ME_CONFIG_MONGODB_SERVER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: mongo-configmap
          #         key: mongo_database_url