# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ja-mongo-db-deploy
#   labels:
#     app: ja-mongo-db
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ja-mongo-db
#   template:
#     metadata:
#       labels:
#         app: ja-mongo-db
#     spec:
#       containers:
#       - image: mongo
#         name: mongo
#         ports:
#         - containerPort: 27017
#         env:
#         - name: MONGO_INITDB_ROOT_USERNAME
#           valueFrom:
#             secretKeyRef:
#               name: mongo-creds
#               key: mongodbadmin-username
#         - name: MONGO_INITDB_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mongo-creds
#               key: mongodbadmin-password