  apiVersion: v1
  kind: Secret
  metadata:
    name: mongo-creds
  type: Opaque
  data:   #jausername japassword
    mongodbadmin-username: amF1c2VybmFtZQ==
    mongodbadmin-password: amFwYXNzd29yZA==