#!/bin/bash
sudo curl -O https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py --user
sudo yum install -y git
chmod 500 /home/ec2-user/.ssh/id_ed25519
cd /home/ec2-user/
sudo ssh-keygen -F github.com || ssh-keyscan github.com >> /home/ec2-user/.ssh/known_hosts
chmod 666 /home/ec2-user/.ssh/known_hosts
sudo cat /home/ec2-user/.ssh/known_hosts
pip3 install flask
cd JaFlaskWebDbApp/
pip3 install -r requirements.txt
FLASK_APP=app.py flask run --host='0.0.0.0' --port=5000