apiVersion: apps/v1
kind: Deployment
metadata:
  name: ja-flask-app-deployment
  labels:
    app: ja-flask-app
  namespace: ja-env2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ja-flask-app
  template:
    metadata:
      labels:
        app: ja-flask-app
    spec:
      containers:
        - name: flask-app-image
          image: us-central1-docker.pkg.dev/playground-s-11-5808d1f1/ja-repo-playground-s-11-5808d1f1/flask-app:staging
          ports:
            - containerPort: 8080
          # env:
          #   - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-creds
          #         key: mongodbadmin-username
          #   - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: mongo-creds
          #         key: mongodbadmin-password
          #   - name: ME_CONFIG_MONGODB_SERVER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: mongo-configmap
          #         key: mongo_database_url